### ISSUE TITLE
update in login for admin and dipatch each time to html .

### ISSUE THREAD

**Issue by harshahs19s** [Cilia-Technologies/EclipsePhotoApp#1]
HI,
just compare a login for admin , we are not storing any admin credential in db just comapare with static value uname= admin password=nutri , and i think as per my suggestion you need to make a proper dispatch like for success userlogin dispatch directly to index.html and for admin admin.html and from that file if any form submission or any listing form db will call the servlet on that time before i done i change file type to index.jsp and i can exicute the query in jsp only . 

**and i will do at admin side to list the users and if he click on user i will dispatch and show the user details in admin page**

if anything replay back

**Comment by gravitejaa** [comment]
completed
